<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="AwesomeAssertions" Version="9.4.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="NUnit" Version="4.5.1" />
	  <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\D2L.Hypermedia.Siren\D2L.Hypermedia.Siren.csproj" />
	</ItemGroup>
</Project>