<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\MatchersTests.cs" Link="MatchersTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\SirenActionTests.cs" Link="SirenActionTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\SirenEntityBuilderTests.cs" Link="SirenEntityBuilderTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\SirenEntityTests.cs" Link="SirenEntityTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\SirenFieldTests.cs" Link="SirenFieldTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\SirenLinkTests.cs" Link="SirenLinkTests.cs" />
		<Compile Include="..\D2L.Hypermedia.Siren.Tests\TestHelpers.cs" Link="TestHelpers.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.4.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\D2L.Hypermedia.Siren\D2L.Hypermedia.Siren.csproj" />
	</ItemGroup>

</Project>