name: Main

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

env:
  VERSION_PREFIX: 2.3.0

jobs:
  all:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:

      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-dotnet

      - run: dotnet tool restore

      - name: Generate version properties
        run: dotnet ci-version-properties --output VersionInfo.props && cat VersionInfo.props

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build
        
      - name: Pack
        run: dotnet pack -c Release --no-build

      - name: Archive
        uses: Brightspace/third-party-actions@actions/upload-artifact
        with:
          name: D2L.Hypermedia.Siren.${{ github.sha }}
          path: '**/*.symbols.nupkg'
