name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  all:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:

      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-dotnet
        with:
          dotnet-version: 7.0.x
      - uses: Brightspace/third-party-actions@NuGet/setup-nuget 
 
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        run: nuget restore D2L.Hypermedia.Siren

      - name: Build
        run: msbuild -p:Configuration=Release D2L.Hypermedia.Siren

      - name: Test
        run: dotnet test D2L.Hypermedia.Siren.Tests -c Release --no-build
        
      - name: Pack
        run: nuget pack D2L.Hypermedia.Siren -Properties Configuration=Release

      - name: Archive
        uses: Brightspace/third-party-actions@actions/upload-artifact
        with:
          name: D2L.Hypermedia.Siren.${{ github.sha }}
          path: '**/D2L.Hypermedia.Siren.*.nupkg'
